config/routes.rb
Spina::Checkout::Engine.routes.draw do

  # Success page!
  resources :success, controller: "success", only: [:show] do
    member do
      # Waiting for payment processing
      get :waiting
    end
  end

  # Canceling order
  resource :cancel_and_duplicate, controller: "cancel_and_duplicate"

  # Shopping cart
  resources :order_items
  resource :empty_cart, controller: "empty_cart", only: [:destroy]
  
  # Delivery date
  resource :delivery_date, controller: "delivery_date"

  # Existing customer account
  resource :existing_customer_account, controller: "existing_customer_account"

  # Discounts & giftcards
  resources :codes
  resources :gift_cards, only: [:destroy]
  resource :discount, only: [:destroy]

  # Sidebar specific controllers
  namespace :sidebar do
    # Fetch summary using javascript to speed up checkout
    resource :summary, controller: 'summary', only: [:show]

    # Infinite scrolling of order items in sidebar
    resources :order_items
  end

  # Login
  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  delete :logout, to: 'sessions#destroy'
  
  # Wizard (route with least priority)
  resources :wizard, path: '/'
end

app/controllers/spina/checkout/order_items_controller.rb
module Spina
  module Checkout
    class OrderItemsController < CheckoutController
      before_action :current_order_building?

      def update
        @order_item = current_order.order_items.find(params[:id])
        @order_item.update(quantity: params[:quantity])
        head :ok
      end

      def destroy
        @order_item = current_order.order_items.find(params[:id])
        @order_item.destroy
        redirect_to wizard_path(:shopping_cart)
      end

      private

        def current_order_building?
          raise unless current_order.building?
        end

    end
  end
end

app/controllers/spina/checkout/sidebar/order_items_controller.rb
module Spina
  module Checkout
    module Sidebar
      class OrderItemsController < CheckoutController

        def index
          @order_items = current_order.order_items.order(:id).page(params[:page]).per(11)

          respond_to do |format|
            format.js
            format.html { render layout: false }
          end
        end

      end
    end
  end
end

app/controllers/spina/checkout/sidebar/summary_controller.rb
module Spina
  module Checkout
    module Sidebar
      class SummaryController < CheckoutController
        before_action :set_defaults, if: -> { Spina::Checkout.config.use_default_delivery_option }

        def show
          render layout: false
        end

      end
    end
  end
end

app/views/spina/checkout/sidebar/order_items/_list.html.haml
.sidebar-products-list
  = render partial: 'spina/checkout/sidebar/order_item', collection: current_order.order_items.order(:id).limit(11)
.sidebar-products-navigation
  - if current_order.order_items.size > 11
    = link_to t("spina.checkout.load_more_products"), sidebar_order_items_path(page: 2), class: 'button button-white button-block button-small', data: {remote: true}

app/views/spina/checkout/sidebar/order_items/index.html.haml
= render 'list'

app/views/spina/checkout/sidebar/order_items/index.js.erb
document.querySelector(".sidebar-products-list").insertAdjacentHTML("beforeend", "<%=j render partial: 'spina/checkout/sidebar/order_item', collection: @order_items %>")

document.querySelector(".sidebar-products-navigation").innerHTML = "<%=j link_to 'Volgende producten', spina_checkout.sidebar_order_items_path(page: params[:page].to_i + 1), class: 'button button-white button-block button-small', data: {remote: true} %>"