config/routes.rb
Spina::Checkout::Engine.routes.draw do

  # Success page!
  resources :success, controller: "success", only: [:show] do
    member do
      # Waiting for payment processing
      get :waiting
    end
  end

  # Canceling order
  resource :cancel_and_duplicate, controller: "cancel_and_duplicate"

  # Shopping cart
  resources :order_items
  resource :empty_cart, controller: "empty_cart", only: [:destroy]
  
  # Delivery date
  resource :delivery_date, controller: "delivery_date"

  # Existing customer account
  resource :existing_customer_account, controller: "existing_customer_account"

  # Discounts & giftcards
  resources :codes
  resources :gift_cards, only: [:destroy]
  resource :discount, only: [:destroy]

  # Sidebar specific controllers
  namespace :sidebar do
    # Fetch summary using javascript to speed up checkout
    resource :summary, controller: 'summary', only: [:show]

    # Infinite scrolling of order items in sidebar
    resources :order_items
  end

  # Login
  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  delete :logout, to: 'sessions#destroy'
  
  # Wizard (route with least priority)
  resources :wizard, path: '/'
end

app/controllers/spina/checkout/sidebar/order_items_controller.rb
module Spina
  module Checkout
    module Sidebar
      class OrderItemsController < CheckoutController

        def index
          @order_items = current_order.order_items.order(:id).page(params[:page]).per(11)

          respond_to do |format|
            format.js
            format.html { render layout: false }
          end
        end

      end
    end
  end
end

app/controllers/spina/checkout/sidebar/summary_controller.rb
module Spina
  module Checkout
    module Sidebar
      class SummaryController < CheckoutController
        before_action :set_defaults, if: -> { Spina::Checkout.config.use_default_delivery_option }

        def show
          render layout: false
        end

      end
    end
  end
end

app/views/spina/checkout/sidebar/summary/_blank_state.html.haml
/ Discount
- if current_order.discount.present?
  .sidebar-summary-line.text-success
    .pull-right= loading_gif
    %span.text-success= current_order.discount.description

/ Placeholder
- if lookup_context.exists? "spina/checkout/sidebar/_before_subtotal_blank_state"
  = render partial: "spina/checkout/sidebar/before_subtotal_blank_state"

/ Subtotal
.sidebar-summary-line
  .pull-right= loading_gif

  - if current_order.prices_include_tax?
    = Spina::Shop::Order.human_attribute_name(:sub_total)
  - else
    = Spina::Shop::Order.human_attribute_name(:sub_total_excl_tax)

/ Delivery costs
- if current_order.delivery_option.present?
  .sidebar-summary-line
    .pull-right= loading_gif
    = Spina::Shop::Order.human_attribute_name(:delivery_price)

/ Tax (only if order doesn't include tax)
- if !current_order.prices_include_tax?
  .sidebar-summary-line
    .pull-right= loading_gif
    =t 'spina.checkout.tax', rate: ''

/ Total
.sidebar-summary-line{class: ('sidebar-summary-line-big' unless current_order.gift_cards.any?)}
  .pull-right= loading_gif
  = Spina::Shop::Order.human_attribute_name(:total)

/ Gift cards
- if current_order.gift_cards.any?
  .sidebar-summary-line.text-success
    %span.text-success
      .pull-right{style: "position: absolute"}= loading_gif
      = Spina::Shop::GiftCard.model_name.human

  .sidebar-summary-line.sidebar-summary-line-big
    .pull-right= loading_gif
    = Spina::Shop::Order.human_attribute_name(:to_be_paid)

/ Codes form
= render partial: "spina/checkout/sidebar/summary/codes_form" if current_order.building?

- if current_order.requires_shipping?
  / Delivery date if the order is shipped
  .sidebar-delivery
    .sidebar-summary-line
      .pull-right
      =t "spina.checkout.expected_delivery"

app/views/spina/checkout/sidebar/summary/_codes_form.html.haml
%div{style: "margin: 12px 0", data: {controller: "codes", url: codes_path, invalid_code: t("spina.checkout.invalid_code")}}
  = button_tag type: :button, class: 'button button-white button-mini', data: {action: "codes#showForm"} do
    %i.icon.icon-plus
    - if current_order.discount.present?
      =t "spina.checkout.gift_card"
    - else
      =t "spina.checkout.gift_card_or_discount"
  .form-group{data: {target: "codes.form"}}
    .input-wrapper{style: 'background: rgba(255, 255, 255, .75)'}
      = text_field_tag :code, nil, class: 'input-small', placeholder: (current_order.discount.present? ? t("spina.checkout.gift_card") : t("spina.checkout.gift_card_or_discount")), data: {target: "codes.input", action: "keydown->codes#pressEnter blur->codes#addCode"}

    = button_tag type: :button, class: 'button button-small button-white', style: "background: none; font-size: 16px; display: flex; align-items: center" do
      %i.icon.icon-plus

app/views/spina/checkout/sidebar/summary/show.html.haml
/ Discount
- if current_order.discount.present?
  .sidebar-summary-line.text-success
    .pull-right
      = number_to_currency current_order.order_total - current_order.order_total_without_discount
    %span.text-success
      = current_order.discount.description
      - if current_order.building?
        = link_to discount_path, class: 'button button-mini', data: {method: :delete, remote: true} do
          &times;

/ Placeholder
- if lookup_context.exists? "spina/checkout/sidebar/_before_subtotal"
  = render partial: "spina/checkout/sidebar/before_subtotal"

/ Subtotal
.sidebar-summary-line
  .pull-right
    - if current_order.discount.present?
      %span{style: "text-decoration: line-through; opacity: .5; font-weight: 400"}= number_to_currency current_order.order_total_without_discount
      = number_to_currency current_order.order_total
    - else
      = number_to_currency current_order.order_total

  - if current_order.prices_include_tax?
    = Spina::Shop::Order.human_attribute_name(:sub_total)
  - else
    = Spina::Shop::Order.human_attribute_name(:sub_total_excl_tax)

/ Delivery costs
.sidebar-summary-line
  .pull-right
    - if current_order.delivery_option.nil?
      –
    - else
      - if current_order.delivery_price.zero?
        %strong.text-success=t 'spina.checkout.free'
      - else
        = number_to_currency current_order.delivery_price
  = Spina::Shop::Order.human_attribute_name(:delivery_price)

/ Tax (only if order doesn't include tax)
- if !current_order.prices_include_tax?
  .sidebar-summary-line
    - if current_order.vat_reverse_charge?
      .pull-right=t 'spina.checkout.vat_reverse_charge'
      &nbsp;
    - else
      - current_order.tax_amount_by_rates.each do |rate, tax|
        .sidebar-summary-line
          .pull-right= number_to_currency tax[:tax_amount]
          =t 'spina.checkout.tax', rate: rate.round

/ Total
.sidebar-summary-line{class: ('sidebar-summary-line-big' unless current_order.gift_cards.any?)}
  .pull-right= number_to_currency current_order.total
  = Spina::Shop::Order.human_attribute_name(:total)

/ Gift cards
- if current_order.gift_cards.any?
  - if current_order.building?
    - current_order.gift_card_usage_for_order.each do |gift_card|
      .sidebar-summary-line.text-success
        .pull-right= number_to_currency gift_card[:gift_card].remaining_balance * -1
        = Spina::Shop::GiftCard.model_name.human
        = link_to gift_card_path(gift_card[:gift_card]), class: 'button button-mini', data: {method: :delete, remote: true} do
          %i.icon.icon-trash

  - else
    .sidebar-summary-line.text-success
      = Spina::Shop::GiftCard.model_name.human
      = number_to_currency current_order.gift_card_amount

  .sidebar-summary-line.sidebar-summary-line-big
    .pull-right= number_to_currency current_order.to_be_paid
    = Spina::Shop::Order.human_attribute_name(:to_be_paid)

- if Spina::Checkout.config.codes_form
  / Codes form
  = render "codes_form" if current_order.building?

- if Spina::Checkout.config.delivery_date_estimation && current_order.requires_shipping?
  / Delivery date if the order is shipped
  .sidebar-delivery
    .sidebar-summary-line{data: {controller: 'delivery-date', delivery_date_url: delivery_date_path}}
      .pull-right{data: {target: 'delivery-date.date'}}
      =t "spina.checkout.expected_delivery"