config/routes.rb
Spina::Checkout::Engine.routes.draw do

  # Success page!
  resources :success, controller: "success", only: [:show] do
    member do
      # Waiting for payment processing
      get :waiting
    end
  end

  # Canceling order
  resource :cancel_and_duplicate, controller: "cancel_and_duplicate"

  # Shopping cart
  resources :order_items
  resource :empty_cart, controller: "empty_cart", only: [:destroy]
  
  # Delivery date
  resource :delivery_date, controller: "delivery_date"

  # Existing customer account
  resource :existing_customer_account, controller: "existing_customer_account"

  # Discounts & giftcards
  resources :codes
  resources :gift_cards, only: [:destroy]
  resource :discount, only: [:destroy]

  # Sidebar specific controllers
  namespace :sidebar do
    # Fetch summary using javascript to speed up checkout
    resource :summary, controller: 'summary', only: [:show]

    # Infinite scrolling of order items in sidebar
    resources :order_items
  end

  # Login
  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  delete :logout, to: 'sessions#destroy'
  
  # Wizard (route with least priority)
  resources :wizard, path: '/'
end

app/controllers/spina/checkout/cancel_and_duplicate_controller.rb
module Spina
  module Checkout
    class CancelAndDuplicateController < CheckoutController
      before_action :set_order
    
      def create
        @order.transition_to!(:cancelled, user: @order.billing_name, ip_address: request.remote_ip)
        session[:order_id] = @order.duplicate&.id
        redirect_to wizard_path(:payment)
      end
      
      private
      
        def set_order
          @order = current_order
        end
    
    end
  
  end
end

app/controllers/spina/checkout/checkout_controller.rb
module Spina
  module Checkout
    class CheckoutController < ActionController::Base
      include Spina::Shop::CurrentOrder

      protect_from_forgery with: :exception
      
      layout 'spina/checkout/checkout'
      
      private
      
        def set_defaults
          current_order.delivery_option_id ||= current_order.delivery_options.first.id
          current_order.payment_method ||= current_order.payment_methods.first
        end
        
    end
  end
end

app/controllers/spina/checkout/codes_controller.rb
module Spina
  module Checkout
    class CodesController < CheckoutController
      before_action :current_order_building?

      def new
      end

      def create
        if discount.present?
          current_order.update(discount: discount)
          head :ok
        elsif gift_card && !current_order.gift_cards.include?(gift_card)
          current_order.gift_cards << gift_card
          current_order.save
          head :ok
        else
          head :not_found
        end
      end

      private

        def current_order_building?
          raise unless current_order.building?
        end

        def discount
          @discount ||= Spina::Shop::Discount.active.find_by(code: params[:code])
        end

        def gift_card
          @gift_card ||= Spina::Shop::GiftCard.available.find_by(code: code_param)
        end

        def code_param
          params[:code].gsub(/\s|-/, "")
        end

    end
  end
end

app/controllers/spina/checkout/delivery_date_controller.rb
module Spina
  module Checkout
    class DeliveryDateController < CheckoutController
    
      def show
        date = current_order.soonest_delivery_date
        date_in_words = if date == Date.tomorrow
          "morgen, #{l(date, format: "%d %B")}"
        elsif date
          l(date, format: "%A %d %B")
        end
        render json: {date: date_in_words}
      end
    
    end
  end
end

app/controllers/spina/checkout/discounts_controller.rb
module Spina
  module Checkout
    class DiscountsController < CheckoutController
      before_action :current_order_building?

      def destroy
        current_order.update(discount: nil)
        render js: "document.querySelector('.sidebar-summary').controller.fetchSummary(); document.querySelector('.sidebar-products').controller.fetchProductList()"
      end

      private

        def current_order_building?
          raise unless current_order.building?
        end

    end
  end
end

app/controllers/spina/checkout/empty_cart_controller.rb
module Spina
  module Checkout
    class EmptyCartController < CheckoutController
      before_action :current_order_building?

      def destroy
        current_order.order_items.destroy_all
        redirect_to wizard_path(:shopping_cart)
      end

      private

        def current_order_building?
          raise unless current_order.building?
        end

    end
  end
end

app/controllers/spina/checkout/existing_customer_account_controller.rb
module Spina::Checkout
  class ExistingCustomerAccountController < CheckoutController

    def create
      @customer_account = Spina::Shop::CustomerAccount.find_by(email: params[:email])

      if @customer_account.present?
        render layout: false
      else
        head :not_found 
      end
    end

  end
end

app/controllers/spina/checkout/gift_cards_controller.rb
module Spina
  module Checkout
    class GiftCardsController < CheckoutController
      before_action :current_order_building?

      def destroy
        @gift_card = current_order.gift_cards.find(params[:id])
        current_order.gift_cards.delete(@gift_card)
        current_order.save
        render js: "document.querySelector('.sidebar-summary').controller.fetchSummary(); document.querySelector('.sidebar-products').controller.fetchProductList()"
      end

      private

        def current_order_building?
          raise unless current_order.building?
        end

    end
  end
end

app/controllers/spina/checkout/order_items_controller.rb
module Spina
  module Checkout
    class OrderItemsController < CheckoutController
      before_action :current_order_building?

      def update
        @order_item = current_order.order_items.find(params[:id])
        @order_item.update(quantity: params[:quantity])
        head :ok
      end

      def destroy
        @order_item = current_order.order_items.find(params[:id])
        @order_item.destroy
        redirect_to wizard_path(:shopping_cart)
      end

      private

        def current_order_building?
          raise unless current_order.building?
        end

    end
  end
end

app/controllers/spina/checkout/sessions_controller.rb
module Spina::Checkout
  class SessionsController < CheckoutController
    before_action :check_logged_in, only: [:new, :create]

    def new; end

    def create
      @customer_account = Spina::Shop::CustomerAccount.find_by(email: params[:email])

      if @customer_account&.authenticate(params[:password])
        login(@customer_account)
        redirect_back(fallback_location: wizard_path(:shopping_cart))
      else
        render :wrong_login
      end
    end

    def destroy
      session[:customer_account_id] = nil
      session[:order_id] = nil
      redirect_back(fallback_location: wizard_path(:shopping_cart))
    end

    private

    def check_logged_in
      redirect_to wizard_path(:shopping_cart) and return if logged_in?
    end
  end
end

app/controllers/spina/checkout/sidebar/order_items_controller.rb
module Spina
  module Checkout
    module Sidebar
      class OrderItemsController < CheckoutController

        def index
          @order_items = current_order.order_items.order(:id).page(params[:page]).per(11)

          respond_to do |format|
            format.js
            format.html { render layout: false }
          end
        end

      end
    end
  end
end

app/controllers/spina/checkout/sidebar/summary_controller.rb
module Spina
  module Checkout
    module Sidebar
      class SummaryController < CheckoutController
        before_action :set_defaults, if: -> { Spina::Checkout.config.use_default_delivery_option }

        def show
          render layout: false
        end

      end
    end
  end
end

app/controllers/spina/checkout/success_controller.rb
module Spina
  module Checkout
    class SuccessController < CheckoutController      
      before_action :set_order
      before_action :redirect_if_building
      before_action :duplicate_if_failed_or_cancelled

      # Enable overriding the template from main app
      layout "spina/checkout/success"
    
      def show
        # Reset the current order
        session[:order_id] = nil
      end

      # When the order is still just confirming, keep reloading this page until the order's state changes
      def waiting
        redirect_to success_path(params[:id]) if @order.received?
      end
      
      private
      
        # Get the order by /success/:id where :id stands for a unique order token
        def set_order
          @order = Spina::Shop::Order.find_by(token: params[:id])
        end

        def redirect_if_building
          redirect_to wizard_path(:shopping_cart) and return if @order.building?  
        end

        # If the order was cancelled or failed,
        # set the duplicated order as the current order
        def duplicate_if_failed_or_cancelled
          if @order.failed? || @order.cancelled?
            session[:order_id] = @order.duplicate&.id
            redirect_to wizard_path(:overview) and return
          end
        end
    
    end
  end
end

app/controllers/spina/checkout/wizard_controller.rb
module Spina
  module Checkout
    class WizardController < CheckoutController
      include Wicked::Wizard
      
      layout 'spina/checkout/wizard'
      
      before_action :redirect_to_root
      before_action :redirect_to_overview
      before_action :set_defaults, only: [:show]

      steps :shopping_cart, :details, :delivery, :payment, :overview

      def show
        render_wizard
      end

      def update
        prepare_validation!
        
        case step
        when :details, :delivery, :payment
          current_order.assign_attributes(order_params)
          additional_updates
        when :overview
          begin
            current_order.transition_to!(:confirming, transition_metadata)
            redirect_to current_order.payment_url and return
          rescue Statesman::GuardFailedError
            redirect_to wizard_path(:shopping_cart) and return
          end
        end
        
        render_wizard current_order
      end

      def additional_updates
        # Placeholder method
        # Do some custom stuff in your main app if you want
      end

      private
        
        def order_params
          detail_params.merge(delivery_params).merge(payment_params)
        end
        
        def detail_params
          params.require(:order).permit(
            :email, 
            :company,
            :first_name, :last_name, 
            :date_of_birth, 
            :separate_delivery_address, 
            :billing_street1, :billing_street2, 
            :billing_house_number, :billing_house_number_addition, 
            :billing_postal_code, :billing_city, :billing_country_id, 
            :delivery_company,
            :delivery_first_name, :delivery_last_name,
            :delivery_street1, :delivery_street2,
            :delivery_house_number, :delivery_house_number_addition,
            :delivery_postal_code, :delivery_city, :delivery_country_id
          )
        end
        
        def delivery_params
          params.require(:order).permit(:delivery_option_id)
        end
        
        def payment_params
          params.require(:order).permit(:payment_method, :payment_issuer)
        end
        
        def redirect_to_root
          redirect_to '/' and return unless current_order
        end
        
        # If the order is already confirming, redirect to the overview page (unless already there)
        def redirect_to_overview
          if current_order.confirming?
            redirect_to wizard_path(:overview) and return unless step == :overview
          end
        end

        def prepare_validation!
          case step
          when :shopping_cart
            current_order.validate_stock = true
          when :details
            current_order.validate_details = true
          when :delivery
            current_order.validate_delivery = true
          when :payment
            current_order.validate_payment = true
          end
        end
        
        def transition_metadata
          {user: current_order.billing_name, ip_address: request.remote_ip}
        end

    end
  end
end

app/helpers/spina/checkout/wizard_helper.rb
module Spina
  module Checkout
    module WizardHelper

      def loading_gif
        image_tag("spina/checkout/loading.gif", width: 24)
      end
      
      def product_image_tag(orderable, variant_options = {}, html_options = {})
        image = get_first_product_image(orderable)
        if image && image.file.attached?
          image_tag main_app.url_for(image.file.variant(variant_options)), html_options
        end
      end

      def checkout_field(form_builder, name, options = {})
        value = options[:value] || form_builder.object.send(name) || options[:default]
        type = options[:type] || "text"

        # .input-wrapper classes
        input_wrapper_classes = ["input-wrapper"]
        input_wrapper_classes << "input-wrapper-#{options[:size]}" if options[:size].present?
        input_wrapper_classes << "focused" if value.present?
        input_wrapper_class = input_wrapper_classes.join(" ")

        # .input-wrapper data attribute
        data_attribute = {
          label: form_builder.object.class.human_attribute_name(name),
          controller: "input"
        }

        # Checkout field wrapped in .input-wrapper div
        content_tag(:div, class: input_wrapper_class, data: data_attribute) do
          targets = ["input.field"]
          targets << "validate.required" if options[:required]
          targets << "date.field" if options[:date]
          targets << options[:target] if options[:target]

          actions = ["keyup->input#placeholder", "change->input#placeholder"]
          actions << "blur->validate#validateField" if options[:required]
          actions << "date#change" if options[:date]
          actions << options[:action] if options[:action]
          
          # Convert to formatted date
          value = I18n.l(value) if options[:date] && value.present?

          form_builder.text_field(name, {
            type: type, 
            value: value,
            disabled: options[:disabled],
            data: {
              target: targets.join(" "),
              action: actions.join(" "),
              name: name,
              validate: options[:required]
            }
          })
        end
      end

      def form_errors(form_object, *attributes)
        attributes.map do |attribute|
          next if form_object.errors[attribute].blank?
          { attribute: attribute, message: "#{form_object.class.human_attribute_name attribute} #{form_object.errors[attribute][0]}" }
        end.compact
      end

      def form_errors(form_object, *attributes)
        attributes.map do |attribute|
          next if form_object.errors[attribute].blank?
          content_tag(:div, class: 'form-error', data: {target: 'validate.errorMessage', attribute: attribute}) do
            "#{form_object.class.human_attribute_name attribute} #{form_object.errors[attribute][0]}"
          end
        end.compact.join("\n").html_safe
      end
      
      private
      
        def get_first_product_image(orderable)
          return nil if orderable.is_a? Spina::Shop::CustomProduct
          image = orderable.product_images.ordered.first
          if image.nil? && orderable.is_a?(Spina::Shop::Product)
            image = orderable.children.joins(:product_images).first&.product_images&.ordered&.first || orderable.root.product_images&.ordered&.first
          end
          image
        end

    end
  end
end

app/views/spina/checkout/wizard/_address_fields.html.haml
%div
  .form-group
    = checkout_field(f, "#{address_type}_street1", size: :large, required: true, default: current_customer&.default_address&.street1)
    = checkout_field(f, "#{address_type}_house_number", required: true, default: current_customer&.default_address&.house_number)
    = checkout_field(f, "#{address_type}_house_number_addition", default: current_customer&.default_address&.house_number_addition)

  .form-group
    = checkout_field(f, "#{address_type}_postal_code", required: true, default: current_customer&.default_address&.postal_code)
    = checkout_field(f, "#{address_type}_city", required: true, default: current_customer&.default_address&.city)

  .form-group
    .input-wrapper.focused{data: {label: Spina::Shop::Order.human_attribute_name("#{address_type}_country")}}
      .form-dropdown
        = f.select "#{address_type}_country_id", Spina::Shop::Country.pluck(:name, :id), {}, data: {target: 'validate.country'}

app/views/spina/checkout/wizard/_date_of_birth_fields.html.haml
.form-group
  = checkout_field(f, :date_of_birth, required: true, date: true, default: current_customer&.date_of_birth)

.form-errors= form_errors(f.object, "date_of_birth")

app/views/spina/checkout/wizard/_delivery_option.html.haml
- if lookup_context.exists? "spina/checkout/delivery_options/_#{delivery_option.name.parameterize}"
  = render partial: "spina/checkout/delivery_options/#{delivery_option.name.parameterize}", locals: {f: f, delivery_option: delivery_option}
- else
  = render partial: "spina/checkout/delivery_options/default", locals: {f: f, delivery_option: delivery_option}

app/views/spina/checkout/wizard/_order_item.html.haml
.shopping-cart-item
  .shopping-cart-item-image
    = product_image_tag order_item.orderable, {resize: '160x160'}
    
  .shopping-cart-item-name
    - if order_item.is_product?
      = link_to order_item.orderable.root.materialized_path, data: {turbo: false} do
        = order_item.orderable.name
        %small
          - if order_item.orderable.variant?
            = order_item.orderable.variant_name
        %strong= number_to_currency order_item.unit_price
    - else
      = link_to order_item.orderable.materialized_path, data: {turbo: false} do
        = order_item.orderable.name
        %small &nbsp;
        %strong= number_to_currency order_item.unit_price

    - if !order_item.in_stock?
      .text-danger{style: 'font-weight: 500'}=t "spina.checkout.out_of_stock"

    - if !order_item.live?
      .text-danger{style: 'font-weight: 500'}=t "spina.checkout.unavailable"

  .shopping-cart-item-action
    = link_to order_item_path(order_item), data: {method: :delete} do
      %i.icon.icon-trash

  .shopping-cart-item-quantity
    .form-group
      = button_tag type: :button, class: 'button button-outline button-small', data: {action: "shopping-cart#subtract"} do
        %i.icon.icon-minus{style: "font-size: 13px"}
      .input-wrapper
        = text_field_tag :quantity, order_item.quantity, class: 'input-small', data: {target: "shopping-cart.quantity", action: "shopping-cart#addToCart", order_item_url: order_item_path(order_item), maximum: (order_item.orderable.stock_level if order_item.orderable.stock_enabled?)}
      = button_tag type: :button, class: 'button button-primary button-small', data: {action: "shopping-cart#add"} do
        %i.icon.icon-plus

app/views/spina/checkout/wizard/_payment_method.html.haml
- if lookup_context.exists? "spina/checkout/payment_methods/_#{payment_method}"
  = render partial: "spina/checkout/payment_methods/#{payment_method}", locals: {f: f, payment_method: payment_method}
- else
  = render partial: "spina/checkout/payment_methods/default", locals: {f: f, payment_method: payment_method}

app/views/spina/checkout/wizard/_shopping_cart_list.html.haml
= render partial: 'order_item', collection: current_order.order_items.order(:id)

app/views/spina/checkout/wizard/delivery.html.haml
.overflow-container{data: {controller: "analytics", checkout_step: 3}}
  = form_with model: current_order, url: wizard_path, method: :put, class: 'container', local: true do |f|
    .main-content
      %h2.heading-2.hide-mobile=t 'spina.checkout.steps.delivery'
      
      = render partial: 'spina/checkout/shared/notifications'

      .form-group
        .form-options
          = render partial: 'delivery_option', collection: current_order.delivery_options, locals: {f: f}

      .form-group{style: "margin-top: 30px"}
        = link_to wizard_path('details'), class: 'button button-link checkout-back-link', style: 'padding-left: 0' do
          %i.icon.icon-arrow-left
          %span=t 'spina.checkout.back'

    .sidebar= render partial: 'spina/checkout/sidebar/sidebar'

app/views/spina/checkout/wizard/details.html.haml
.overflow-container{data: {controller: "analytics", checkout_step: 2}}
  = form_with model: current_order, url: wizard_path, method: :put, class: 'container', local: true, data: {controller: 'validate'} do |f|
    .main-content{data: {controller: "details", login_popup: Spina::Checkout.config.login_popup}}
      %h2.heading-2.hide-mobile=t 'spina.checkout.steps.details'

      -#= render partial: 'spina/checkout/shared/notifications'

      .form-group
        = checkout_field(f, :email, target: "details.email", action: "details#checkExistingCustomerAccount", required: "email", default: current_customer&.email)

      .form-errors= form_errors(f.object, :email)

      - unless logged_in?
        %div{data: {target: "details.loginNotification", existing_customer_account_path: spina_checkout.existing_customer_account_path}}
          = link_to t("spina.checkout.account_login"), login_path, style: "font-size: 15px", data: {remote: true, target: "details.loginLink"}

      %h2.heading-2{style: "margin-top: 30px"}=t "spina.checkout.billing_address"

      - if f.object.business?
        .form-group
          = checkout_field(f, :company, required: true, default: current_customer&.company)

      .form-group
        = checkout_field(f, :first_name, required: true, default: current_customer&.first_name)
        = checkout_field(f, :last_name, required: true, default: current_customer&.last_name)

      .form-errors= form_errors(f.object, :first_name, :last_name)

      / Address fields
      = render partial: 'address_fields', locals: {f: f, address_type: "billing"}

      %div
        %h2.heading-2{style: "margin-top: 30px"}=t "spina.checkout.delivery_address"
        .form-group
          .button-group
            %label.form-label.button.button-white.button-small.button-radio-button
              = f.radio_button :separate_delivery_address, false, data: {action: 'details#toggleSeparateDeliveryAddress'}
              =t 'spina.checkout.delivery_address_same_as_billing_address'

            %label.form-label.button.button-white.button-small.button-radio-button
              = f.radio_button :separate_delivery_address, true, data: {action: 'details#toggleSeparateDeliveryAddress', target: 'details.separateDeliveryAddress'}
              = Spina::Shop::Order.human_attribute_name(:separate_delivery_address)
        
        %div{data: {target: "details.deliveryAddress", controller: "address-book"}}
          - if current_customer&.addresses&.many?
            .form-group
              .input-wrapper.focused{data: {label: Spina::Shop::Order.human_attribute_name(:separate_delivery_address)}}
                .form-dropdown
                  = select_tag :address_book, options_for_select(current_customer.addresses.where(country_id: current_customer.country_id).map{|address| ["#{address.address}, #{address.city} (#{address.name})", address.id, {data: {first_name: address.first_name, last_name: address.last_name, company: address.company, postal_code: address.postal_code, house_number: address.house_number, house_number_addition: address.house_number_addition, city: address.city, street: address.street1}}]}), {include_blank: t("spina.checkout.choose_from_address_book"), data: {action: "address-book#chooseAddress"}}

          .form-group
            = checkout_field(f, :delivery_company)
          .form-group
            = checkout_field(f, :delivery_first_name, required: true)
            = checkout_field(f, :delivery_last_name, required: true)

          .form-errors= form_errors(f.object, :delivery_first_name, :delivery_last_name)
            
          = render partial: 'address_fields', locals: {f: f, address_type: "delivery"}

      - if Spina::Checkout.config.must_be_of_age
        %h2.heading-2{style: "margin-top: 30px"}= Spina::Shop::Order.human_attribute_name(:date_of_birth)

        = render partial: "date_of_birth_fields", locals: {f: f}

      .form-group.hide-mobile{style: "margin-top: 30px"}
        = link_to wizard_path('shopping_cart'), class: 'button button-link checkout-back-link', style: 'padding-left: 0' do
          %i.icon.icon-arrow-left
          %span=t 'spina.checkout.back'

    .sidebar= render partial: 'spina/checkout/sidebar/sidebar'

app/views/spina/checkout/wizard/overview.html.haml
.overflow-container{data: {controller: "analytics", checkout_step: 5}}
  = form_with model: current_order, url: wizard_path, method: :put, class: 'container', local: true do |f|
    .main-content
      %h2.heading-2.hide-mobile=t 'spina.checkout.steps.overview'
      
      - if current_order.confirming?
        .notification.notification-info
          =t "spina.checkout.payment_failed"
          %br/
          = link_to t('spina.checkout.payment_failed_try_again'), cancel_and_duplicate_path, data: {method: :post}

      = render partial: 'spina/checkout/shared/notifications'

      .checkout-overview
        .checkout-overview-column
          %h3.heading-3
            - if current_order.requires_shipping?
              = Spina::Shop::Order.human_attribute_name(:delivery_address)
            - else
              =t "spina.checkout.overview_pickup"
          
          .checkout-overview-address
            - if current_order.requires_shipping?
              = current_order.delivery_name
              %br/
              = current_order.delivery_address
              %br/
              = [current_order.delivery_postal_code, current_order.delivery_city].join(", ")
              (#{current_order.delivery_country&.code})
            - else
              - account = Spina::Account.first
              = account.name
              %br/
              = account.address
              %br/
              = [account.postal_code, account.city].join(" ")
              
          - if current_order.requires_shipping?
            %small= link_to t('spina.checkout.edit_details'), wizard_path('details') if current_order.building?
          - else
            %small= link_to t('spina.checkout.edit_delivery_address'), wizard_path('delivery') if current_order.building?
          
          .checkout-overview-partner
            %h4.heading-3
              - if current_order.requires_shipping?
                =t "spina.checkout.overview_delivery"
              - else
                =t "spina.checkout.overview_pickup"
            
            %div{style: "display: flex; align-items: center"}
              = image_tag "spina/checkout/carriers/#{current_order.delivery_option.carrier.parameterize}.svg"
              =t "delivery_options.#{current_order.delivery_option.name.parameterize}.name"

            %small= link_to t('spina.checkout.edit_delivery'), wizard_path('delivery') if current_order.building?
            
        .checkout-overview-column
          %h3.heading-3=t 'spina.checkout.billing_address'
          
          .checkout-overview-address
            = current_order.billing_name
            %br/
            = current_order.billing_address
            %br/
            #{current_order.billing_postal_code}, #{current_order.billing_city} (#{current_order.billing_country.code})

          %small= link_to t('spina.checkout.edit_billing_address'), wizard_path('details') if current_order.building?
          
          .checkout-overview-partner
            %h4.heading-3=t 'spina.checkout.payment_method'
            - if current_order.payment_issuer.present? && current_order.payment_method == "ideal"
              %div{style: "display: flex; align-items: center"}
                = image_tag "spina/checkout/payment_methods/#{current_order.payment_method.parameterize}/payment_issuers/#{current_order.payment_issuer.parameterize}.png"
                =t "payment_methods.#{current_order.payment_method.parameterize}.payment_issuers.#{current_order.payment_issuer.parameterize}"
               
            - else
              %div{style: "display: flex; align-items: center"}
                = image_tag "spina/checkout/payment_methods/#{current_order.payment_method.parameterize}.svg"
                =t "payment_methods.#{current_order.payment_method.parameterize}.name"

            %small= link_to t('spina.checkout.edit_payment'), wizard_path('payment') if current_order.building?

      / Placeholder
      - if lookup_context.exists? "spina/checkout/wizard/_after_overview"
        = render partial: "spina/checkout/wizard/after_overview"
          
      - if current_order.building?  
        .form-group
          = link_to wizard_path('payment'), class: 'button button-link checkout-back-link', style: 'padding-left: 0' do
            %i.icon.icon-arrow-left
            %span=t 'spina.checkout.back'

    .sidebar= render partial: 'spina/checkout/sidebar/sidebar'

app/views/spina/checkout/wizard/payment.html.haml
.overflow-container{data: {controller: "analytics", checkout_step: 4}}
  = form_with model: current_order, url: wizard_path, method: :put, class: 'container', local: true do |f|
    .main-content
      %h2.heading-2.hide-mobile=t 'spina.checkout.steps.payment'
      
      = render partial: 'spina/checkout/shared/notifications'

      .form-group
        .form-options              
          = render partial: "payment_method", collection: current_order.payment_methods, locals: {f: f}

      .form-group{style: "margin-top: 30px"}
        = link_to wizard_path('delivery'), class: 'button button-link checkout-back-link', style: 'padding-left: 0' do
          %i.icon.icon-arrow-left
          %span=t 'spina.checkout.back'

    .sidebar= render partial: 'spina/checkout/sidebar/sidebar'

app/views/spina/checkout/wizard/shopping_cart.html.haml
.overflow-container{data: {controller: "analytics", checkout_step: 1}}
  = form_with model: current_order, url: wizard_path, method: :put, class: 'container', local: true do |f|
    .main-content{data: {controller: "shopping-cart"}}
      = link_to '/', class: '', style: 'font-size: 14px; padding: 4px; padding-left: 0px; display: inline-block; text-decoration: none', data: {turbo: false} do
        %i.icon.icon-arrow-left
        %span=t 'spina.checkout.back_to_webshop'
      - if current_order.order_items.any?
        %h2.heading-2=t 'spina.checkout.shopping_cart'
      - else
        %h2.heading-2=t 'spina.checkout.empty_shopping_cart'

      = render partial: 'spina/checkout/shared/notifications'

      .shopping-cart-item-list= render 'shopping_cart_list'

      %div{style: 'margin-top: 30px'}
        - if current_order.order_items.any?
          .pull-right
            = link_to empty_cart_path, class: 'button button-white button-mini', data: {method: :delete} do
              %i.icon.icon-trash
              = t("spina.checkout.empty_cart")

    .sidebar
      = render partial: 'spina/checkout/sidebar/sidebar'